config/routes.rb
Rails.application.routes.draw do
  get 'car_selling_coupon/index'

  get 'car_selling_coupon/payment'

  get 'car_selling_coupon/contact'

  get 'car_selling_coupon/thanks'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/car_selling_coupon_controller.rb
class CarSellingCouponController < ApplicationController
  def index
  end

  def payment
  end

  def contact
  end

  def thanks
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/car_selling_coupon_helper.rb
module CarSellingCouponHelper
end

app/views/car_selling_coupon/contact.html.erb
<h1>支付成功<br/>请填写您的联系方式</h1>
<% @title = '填写联系方式' %>
<div class="column row contact">
  <form>
    <div class="row">
      <div class="small-3 columns">
        <label for="name" class="text-right middle">姓名</label>
      </div>
      <div class="small-6 columns end">
        <input type="text" id="name" placeholder="请输入您的姓名" />
      </div>
    </div>
    <div class="row">
      <div class="small-3 columns">
        <label for="mobile" class="text-right middle">手机</label>
      </div>
      <div class="small-6 columns end">
        <input type="text" id="mobile" placeholder="请输入您的手机号" />
      </div>
    </div>
    <div class="row">
      <div class="small-9 small-offset-3 columns">
        <%= link_to '提交', car_selling_coupon_thanks_path, class: 'button' %>
      </div>
    </div>
  </form>
</div>

app/views/car_selling_coupon/index.html.erb
<% @title = '汽车团购优惠券' %>
<div class="column row coupon">
  <h1><%= @title %></h1>
  <ul class="filter">
    <li>
      <span class="field">品牌：</span>
      <ul class="option">
        <li>全部</li>
        <li>比亚迪</li>
        <li>北汽</li>
        <li>江淮</li>
      </ul>
    </li>
    <li>
      <span class="field">类型：</span>
      <ul class="option">
        <li>全部</li>
        <li>纯电</li>
        <li>汽油</li>
        <li>混动</li>
      </ul>
    </li>
    <li>
      <span class="field">排序：</span>
      <ul class="option">
        <li>最新</li>
        <li>面额</li>
        <li>销量</li>
      </ul>
    </li>
    <li>
      <span class="field">搜索：</span>
      <input type="text" placeholder="关键字" class="search" />
    </li>
  </ul>
</div>
<div class="coupon">
  <div class="row">
    <div class="small-9 columns">
      <div class="callout coupon">
        <h3>比亚迪 E6 <small>豪华版</small></h3>
        <p>
          <span class="field">面额：</span>6000元<br/>
          <span class="field">价格：</span><span class="red">500元</span>
        </p>
      </div>
    </div>
    <div class="small-3 columns">
      <%= link_to '购买', car_selling_coupon_payment_path, class: 'success button' %>
    </div>
  </div>
  <div class="row">
    <div class="small-9 columns">
      <div class="callout coupon">
        <h3>比亚迪 E6 <small>精英版</small></h3>
        <p>
          <span class="field">面额：</span>9000元<br/>
          <span class="field">价格：</span><span class="red">500元</span>
        </p>
      </div>
    </div>
    <div class="small-3 columns">
      <button type="button" class="button">购买</button>
    </div>
  </div>
  <div class="row">
    <div class="small-9 columns">
      <div class="callout coupon">
        <h3>比亚迪 E5</h3>
        <p>
          <span class="field">面额：</span>3000元<br/>
          <span class="field">价格：</span><span class="red">500元</span>
        </p>
      </div>
    </div>
    <div class="small-3 columns">
      <button type="button" class="button">购买</button>
    </div>
  </div>
  <div class="row">
    <div class="small-9 columns">
      <div class="callout coupon">
        <h3>比亚迪 S7 Plus <small>旗舰版/尊贵版</small></h3>
        <p>
          <span class="field">面额：</span>9000元<br/>
          <span class="field">价格：</span><span class="red">500元</span>
        </p>
      </div>
    </div>
    <div class="small-3 columns">
      <button type="button" class="button">购买</button>
    </div>
  </div>
</div>

app/views/car_selling_coupon/payment.html.erb
<% @title = '微信支付' %>
<div class="column row payment">
  <div class="callout">
    <h3>微信支付 <small>6000元</small></h3>
    <button type="button" class="button">确定</button>
  </div>
  <div class="go-to-next-page">
    <%= link_to '支付完成后进入下一页', car_selling_coupon_contact_path %>
  </div>
</div>

app/views/car_selling_coupon/thanks.html.erb
<% @title = '感谢您的支持！' %>
<div class="column row thanks">
  <div class="callout">
    <h3>感谢您对比亚迪的支持！</h3>
    <p>4S店的销售顾问将在48小时内和您联系。</p>
    <p>汽车团购优惠券已通过微信公众号发送给您。</p>
  </div>
  <p><%= link_to '返回首页', car_selling_coupon_index_path %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<meta http-equiv="x-ua-compatible" content="ie=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title><%= @title ||= 'Site Name' %></title>
<%= csrf_meta_tags %>
<%= action_cable_meta_tag %>
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
</head>
<body>
<%= yield %>
</body>
</html>